services:
  - type: web
    name: anahain-demo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: MEDICAL_DATA_DIR
        value: /tmp/medical-data
      - key: MEDICAL_ADMIN_USER
        value: medico
      - key: MEDICAL_ADMIN_PASSWORD
        sync: false
